export type KeywordStrategy =
  | "pass-all"
  | "allowlist"
  | "karma"
  | "api-query"
  | "shared-keyword-list";

export interface DataSource {
  id: string;
  name: string;
  type: "rss" | "api";
  url: string;
  domain: string;
  maxItems?: number;
  credibility: number;
  tier: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  keywordFilter: KeywordStrategy;
  allowlistTerms?: string[];
}

export const TIER_LABELS: Record<number, string> = {
  0: "Regulatory",
  1: "Institutional",
  2: "Journalism",
  3: "Community",
  4: "Search",
  5: "Newsletter",
  6: "Data Infrastructure",
};

export const DATA_SOURCES: DataSource[] = [
  // ── T0 — Regulatory ──────────────────────────────────────────
  {
    id: "eu-ai-office",
    name: "EU AI Office / EUR-Lex",
    type: "rss",
    url: "https://ec.europa.eu/newsroom/dae/rss.cfm",
    domain: "Regulatory",
    credibility: 0.93,
    tier: 0,
    keywordFilter: "allowlist",
    allowlistTerms: [
      "ai act", "artificial intelligence act", "regulation 2024/1689",
      "celex", "ai office", "high-risk ai", "ai regulation",
    ],
  },
  {
    id: "nist-ai",
    name: "NIST AI / Federal Register",
    type: "rss",
    url: "https://www.nist.gov/news-events/news/rss.xml",
    domain: "Regulatory",
    credibility: 0.91,
    tier: 0,
    keywordFilter: "allowlist",
    allowlistTerms: [
      "ai act", "ai rmf", "risk management framework",
      "executive order", "artificial intelligence", "ai safety",
      "ai standard", "nist ai",
    ],
  },
  // NOTE: OECD has no public RSS feed or API for AI content.
  // oecd.ai offers only an email newsletter; iLibrary was retired end-2024.
  // Source removed — regulatory/policy coverage provided by EU AI Office,
  // Brookings, RAND, and other T1 sources.

  // ── T1 — Institutional / Research ─────────────────────────────
  {
    id: "arxiv-ai",
    name: "arXiv CS.AI",
    type: "rss",
    url: "https://export.arxiv.org/api/query?search_query=cat:cs.AI+AND+ti:safety&max_results=15&sortBy=submittedDate&sortOrder=descending",
    domain: "AI research",
    maxItems: 15,
    credibility: 0.85,
    tier: 1,
    keywordFilter: "api-query",
  },
  {
    id: "alignment-forum",
    name: "Alignment Forum",
    type: "rss",
    url: "https://www.alignmentforum.org/feed.xml?view=frontpage-rss&karmaThreshold=25",
    domain: "AI safety",
    maxItems: 10,
    credibility: 0.85,
    tier: 1,
    keywordFilter: "pass-all",
  },
  {
    id: "cais-newsletter",
    name: "AI Safety Newsletter (CAIS)",
    type: "rss",
    url: "https://newsletter.safe.ai/feed",
    domain: "AI safety",
    credibility: 0.85,
    tier: 1,
    keywordFilter: "pass-all",
  },
  {
    id: "nature-mach-intel",
    name: "Nature Machine Intelligence",
    type: "rss",
    url: "https://www.nature.com/natmachintell.rss",
    domain: "AI research",
    maxItems: 10,
    credibility: 0.90,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "ai-now-institute",
    name: "AI Now Institute",
    type: "rss",
    url: "https://ainowinstitute.org/category/news/feed",
    domain: "AI policy",
    credibility: 0.85,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "future-of-life",
    name: "Future of Life Institute",
    type: "rss",
    url: "https://futureoflife.org/category/ai/feed/",
    domain: "AI safety",
    credibility: 0.88,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "anthropic-blog",
    name: "Anthropic Research Blog",
    type: "rss",
    url: "https://www.anthropic.com/research.rss",
    domain: "AI safety",
    credibility: 0.88,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "deepmind-blog",
    name: "Google AI Blog",
    type: "rss",
    url: "https://blog.google/technology/ai/rss/",
    domain: "AI safety",
    credibility: 0.85,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "aiid",
    name: "AI Incident Database (AIID)",
    type: "rss",
    url: "https://incidentdatabase.ai/blog/rss.xml",
    domain: "AI harms",
    credibility: 0.85,
    tier: 1,
    keywordFilter: "pass-all",
  },
  {
    id: "miri-blog",
    name: "MIRI Blog",
    type: "rss",
    url: "https://intelligence.org/feed/",
    domain: "AI alignment",
    credibility: 0.82,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "promedmail",
    name: "ProMED (ISID)",
    type: "rss",
    url: "https://promedmail.org/feed/",
    domain: "Biosecurity",
    credibility: 0.90,
    tier: 1,
    keywordFilter: "pass-all",
  },
  {
    id: "who-don",
    name: "WHO Disease Outbreak News",
    type: "rss",
    url: "https://www.who.int/rss-feeds/news-english.xml",
    domain: "Biosecurity",
    credibility: 0.92,
    tier: 1,
    keywordFilter: "pass-all",
  },
  {
    id: "crisis-group",
    name: "International Crisis Group",
    type: "rss",
    url: "https://www.crisisgroup.org/crisiswatch/rss.xml",
    domain: "Geopolitical",
    credibility: 0.88,
    tier: 1,
    keywordFilter: "pass-all",
  },
  {
    id: "wef-agenda",
    name: "WEF Global Risks / Agenda",
    type: "rss",
    url: "https://www.weforum.org/agenda/rss.xml",
    domain: "Geopolitical",
    credibility: 0.85,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "nature-climate",
    name: "Nature Climate Change",
    type: "rss",
    url: "https://www.nature.com/nclimate.rss",
    domain: "Climate",
    credibility: 0.90,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "rand-corp",
    name: "RAND Corporation",
    type: "rss",
    url: "https://www.rand.org/pubs/new.xml",
    domain: "Policy / security",
    credibility: 0.87,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "brookings",
    name: "Brookings Institution",
    type: "rss",
    url: "https://www.brookings.edu/topic/artificial-intelligence/feed/",
    domain: "Policy / AI",
    credibility: 0.87,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "digichina",
    name: "DigiChina (Stanford FSI)",
    type: "rss",
    url: "https://digichina.stanford.edu/news/all/rss",
    domain: "China / AI policy",
    credibility: 0.87,
    tier: 1,
    keywordFilter: "shared-keyword-list",
  },

  // ── T2 — Journalism ──────────────────────────────────────────
  {
    id: "mit-tech-review",
    name: "MIT Technology Review",
    type: "rss",
    url: "https://www.technologyreview.com/feed/",
    domain: "AI journalism",
    credibility: 0.80,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "wired-ai",
    name: "Wired AI",
    type: "rss",
    url: "https://www.wired.com/feed/tag/ai/latest/rss",
    domain: "AI journalism",
    credibility: 0.75,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "ars-ai",
    name: "Ars Technica AI",
    type: "rss",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    domain: "AI journalism",
    credibility: 0.75,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "ieee-spectrum-ai",
    name: "IEEE Spectrum AI",
    type: "rss",
    url: "https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss",
    domain: "AI journalism",
    credibility: 0.80,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "guardian-ai",
    name: "The Guardian AI",
    type: "rss",
    url: "https://www.theguardian.com/technology/artificialintelligenceai/rss",
    domain: "AI journalism",
    credibility: 0.75,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },
  // HealthMap removed — URL was an HTML dashboard page, not an RSS feed.
  // Biosecurity coverage provided by WHO DON, ProMED, STAT News, and CDC.
  {
    id: "stat-news",
    name: "STAT News",
    type: "rss",
    url: "https://www.statnews.com/feed/",
    domain: "Biosecurity",
    credibility: 0.80,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "carbon-brief",
    name: "Carbon Brief",
    type: "rss",
    url: "https://www.carbonbrief.org/feed/",
    domain: "Climate",
    credibility: 0.82,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "climate-central",
    name: "Climate Central",
    type: "rss",
    url: "https://www.climatecentral.org/feed",
    domain: "Climate",
    credibility: 0.78,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "bellingcat",
    name: "Bellingcat",
    type: "rss",
    url: "https://www.bellingcat.com/feed/",
    domain: "Geopolitical",
    credibility: 0.78,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "foreign-policy",
    name: "Foreign Policy",
    type: "rss",
    url: "https://foreignpolicy.com/feed",
    domain: "Geopolitical",
    credibility: 0.78,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "platformer",
    name: "Platformer",
    type: "rss",
    url: "https://www.platformer.news/rss/",
    domain: "AI accountability",
    credibility: 0.78,
    tier: 2,
    keywordFilter: "shared-keyword-list",
  },

  // ── T3 — Community ───────────────────────────────────────────
  {
    id: "verge-ai",
    name: "The Verge AI",
    type: "rss",
    url: "https://www.theverge.com/rss/index.xml",
    domain: "AI tech",
    credibility: 0.65,
    tier: 3,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    type: "rss",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    domain: "AI tech",
    credibility: 0.60,
    tier: 3,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "lesswrong",
    name: "LessWrong",
    type: "rss",
    url: "https://www.lesswrong.com/feed.xml?view=frontpage-rss&karmaThreshold=30",
    domain: "AI safety community",
    credibility: 0.68,
    tier: 3,
    keywordFilter: "karma",
  },
  {
    id: "ea-forum",
    name: "EA Forum / 80,000 Hours",
    type: "rss",
    url: "https://forum.effectivealtruism.org/feed.xml?view=tagRss&tag=ai-safety",
    domain: "AI safety community",
    credibility: 0.72,
    tier: 3,
    keywordFilter: "karma",
  },

  // ── T4 — Search ──────────────────────────────────────────────
  {
    id: "gdelt-ai",
    name: "GDELT DOC API",
    type: "api",
    url: "https://api.gdeltproject.org/api/v2/doc/doc?query=%22AI+risk%22&mode=artlist&timespan=12h&format=json",
    domain: "Media monitoring",
    credibility: 0.50,
    tier: 4,
    keywordFilter: "api-query",
  },
  // NewsAPI removed — requires API key (401 without it), free tier is
  // dev-only with 24h delay. Media coverage already handled by GDELT.

  // ── T5 — Newsletter ──────────────────────────────────────────
  {
    id: "tldr-ai",
    name: "TLDR AI",
    type: "rss",
    url: "https://tldr.tech/ai/rss",
    domain: "AI newsletter",
    maxItems: 20,
    credibility: 0.65,
    tier: 5,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "import-ai",
    name: "Import AI",
    type: "rss",
    url: "https://importai.substack.com/feed",
    domain: "AI newsletter",
    credibility: 0.70,
    tier: 5,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "last-week-in-ai",
    name: "Last Week in AI",
    type: "rss",
    url: "https://lastweekin.ai/feed",
    domain: "AI newsletter",
    credibility: 0.65,
    tier: 5,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "bens-bites",
    name: "Ben's Bites",
    type: "rss",
    url: "https://bensbites.beehiiv.com/feed",
    domain: "AI newsletter",
    credibility: 0.65,
    tier: 5,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "chinai-newsletter",
    name: "ChinAI Newsletter",
    type: "rss",
    url: "https://chinai.substack.com/feed",
    domain: "China / AI",
    credibility: 0.72,
    tier: 5,
    keywordFilter: "shared-keyword-list",
  },
  {
    id: "cdc-mmwr",
    name: "CDC / MMWR",
    type: "rss",
    url: "https://www.cdc.gov/mmwr/rss/mmwrall.xml",
    domain: "Biosecurity",
    credibility: 0.90,
    tier: 5,
    keywordFilter: "pass-all",
  },
  {
    id: "the-batch",
    name: "The Batch (deeplearning.ai)",
    type: "rss",
    url: "https://www.deeplearning.ai/the-batch/rss/",
    domain: "AI newsletter",
    credibility: 0.68,
    tier: 5,
    keywordFilter: "shared-keyword-list",
  },

  // ── T6 — Data Infrastructure ─────────────────────────────────
  {
    id: "semantic-scholar",
    name: "Semantic Scholar API",
    type: "api",
    url: "https://api.semanticscholar.org/graph/v1/paper/search?query=AI+safety&fields=title,year,abstract,url&limit=20",
    domain: "Academic search",
    credibility: 0.65,
    tier: 6,
    keywordFilter: "api-query",
  },
];
